network/api/urls.py
"""SatNOGS Network django rest framework API url routings"""
from django.urls import path
from rest_framework import routers

from network.api import views

ROUTER = routers.DefaultRouter()

ROUTER.register(r'jobs', views.JobView, basename='jobs')
ROUTER.register(r'observations', views.ObservationView, basename='observations')
ROUTER.register(r'stations', views.StationView, basename='stations')
ROUTER.register(r'configuration', views.StationConfigurationView, basename='configuration')
ROUTER.register(r'transmitters', views.TransmitterView, basename='transmitters')

API_URLPATTERNS = ROUTER.urls + [path('station/register', views.station_register_view)]

network/base/urls.py
"""Django base URL routings for SatNOGS Network"""
from django.urls import path, re_path
from django.views.generic import TemplateView

from network.base.views import generic, observation, scheduling, station

BASE_URLPATTERNS = (
    [
        # Generic
        path('', generic.index, name='home'),
        path('about/', TemplateView.as_view(template_name='base/about.html'), name='about'),
        path('robots.txt', generic.robots, name='robots'),
        path('settings_site/', generic.settings_site, name='settings_site'),

        # Observations
        path('observations/', observation.ObservationListView.as_view(), name='observations_list'),
        re_path(
            r'^observations/(?P<observation_id>[0-9]+)/$',
            observation.observation_view,
            name='observation_view'
        ),
        re_path(
            r'^observations/(?P<observation_id>[0-9]+)/delete/$',
            observation.observation_delete,
            name='observation_delete'
        ),
        path(
            'vet-observations/',
            observation.VetObservationsView.as_view(),
            name='vet_observations'
        ),
        path(
            'vet-observations-chunks/',
            observation.VetObservationsChunkListView.as_view(),
            name='vet_observations_chunks'
        ),
        re_path(
            r'^waterfall_vet/(?P<observation_id>[0-9]+)/$',
            observation.waterfall_vet,
            name='waterfall_vet'
        ),
        re_path(
            r'^satellites/(?P<norad_id>[0-9]+)/$',
            observation.satellite_view,
            name='satellite_view'
        ),

        # Stations
        path('stations_all/', station.station_all_view, name='stations_all'),
        path('stations/', station.StationListView.as_view(), name='stations_list'),
        re_path(r'^stations/(?P<station_id>[0-9]+)/$', station.station_view, name='station_view'),
        re_path(
            r'^stations/(?P<station_id>[0-9]+)/delete/$',
            station.station_delete,
            name='station_delete'
        ),
        re_path(
            r'^stations/(?P<station_id>[0-9]+)/delete_future_observations/$',
            station.station_delete_future_observations,
            name='station_delete_future_observations'
        ),
        re_path(
            'stations/register/step(?P<step>1)/$',
            station.station_register,
            name='station_register'
        ),
        re_path(
            'stations/register/step(?P<step>2)/$',
            station.station_register,
            name='station_register'
        ),
        re_path(
            'stations/register/step(?P<step>2)/(?P<station_id>[0-9]+)/$',
            station.station_register,
            name='station_register'
        ),
        path('stations/edit/', station.station_edit, name='station_edit'),
        re_path(
            r'^stations/edit/(?P<station_id>[0-9]+)/$', station.station_edit, name='station_edit'
        ),

        # Scheduling
        path('observations/new/', scheduling.observation_new, name='observation_new'),
        path('prediction_windows/', scheduling.prediction_windows, name='prediction_windows'),
        re_path(
            r'^pass_predictions/(?P<station_id>[\w.@+-]+)/$',
            scheduling.pass_predictions,
            name='pass_predictions'
        ),
        path('scheduling_stations/', scheduling.scheduling_stations, name='scheduling_stations'),
        path('transmitters/', scheduling.transmitters_view, name='transmitters_view'),
    ],
    'base'
)

network/urls.py
"""Base Django URL mapping for SatNOGS Network"""
from allauth import urls as allauth_urls
from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

from network.api.urls import API_URLPATTERNS
from network.base.urls import BASE_URLPATTERNS
from network.users.urls import USERS_URLPATTERNS

urlpatterns = [
    # Base urls
    path('', include(BASE_URLPATTERNS)),
    path('admin/', admin.site.urls),
    path('users/', include(USERS_URLPATTERNS)),
    path('accounts/', include(allauth_urls)),
    path('api/', include(API_URLPATTERNS))
]

# Auth0
if settings.AUTH0:
    urlpatterns += [path('', include('auth0login.urls'))]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

network/users/urls.py
"""Django users URL routings for SatNOGS Network"""
from django.urls import path, re_path

from network.users import views

USERS_URLPATTERNS = (
    [
        path('redirect/', views.UserRedirectView.as_view(), name='redirect_user'),
        path('update/', views.UserUpdateView.as_view(), name='update_user'),
        path('update/token/', views.update_user_token, name='update_user_token'),
        re_path(r'^(?P<username>[\w.@+-]+)/$', views.view_user, name='view_user'),
    ], 'users'
)

network/base/models.py
"""Django database base model for SatNOGS Network"""
import codecs
import re
from datetime import timedelta
from operator import truth

from django.conf import settings
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.files.storage import DefaultStorage
from django.core.validators import MaxLengthValidator, MaxValueValidator, MinLengthValidator, \
    MinValueValidator
from django.db import models
from django.db.models import Count, Q
from django.dispatch import receiver
from django.urls import reverse
from django.utils.html import format_html
from django.utils.timezone import now
from shortuuidfield import ShortUUIDField
from storages.backends.s3boto3 import S3Boto3Storage

from network.base.db_api import DBConnectionError, get_artifact_metadata_by_observation_id
from network.base.managers import ObservationManager
from network.base.utils import bands_from_range
from network.users.models import User

OBSERVATION_STATUSES = (
    ('unknown', 'Unknown'),
    ('good', 'Good'),
    ('bad', 'Bad'),
    ('failed', 'Failed'),
)
STATION_STATUSES = (
    (2, 'Online'),
    (1, 'Testing'),
    (0, 'Offline'),
)
STATION_VIOLATOR_SCHEDULING_CHOICES = (
    (0, 'No one'),
    (1, 'Only Operators'),
    (2, 'Everyone'),
)
SATELLITE_STATUS = ['alive', 'dead', 'future', 're-entered']
TRANSMITTER_STATUS = ['active', 'inactive', 'invalid']
TRANSMITTER_TYPE = ['Transmitter', 'Transceiver', 'Transponder']


def _decode_pretty_hex(binary_data):
    """Return the binary data as hex dump of the following form: `DE AD C0 DE`"""

    data = codecs.encode(binary_data, 'hex').decode('ascii').upper()
    return ' '.join(data[i:i + 2] for i in range(0, len(data), 2))


def _name_obs_files(instance, filename):
    """Return a filepath formatted by Observation ID"""
    return 'data_obs/{0}/{1}'.format(instance.id, filename)


def _name_obs_demoddata(instance, filename):
    """Return a filepath for DemodData formatted by Observation ID"""
    # On change of the string bellow, change it also at api/views.py
    return 'data_obs/{0}/{1}'.format(instance.observation.id, filename)


def _name_observation_data(instance, filename):
    """Return a filepath formatted by Observation ID"""
    return 'data_obs/{0}/{1}/{2}/{3}/{4}/{5}'.format(
        instance.start.year, instance.start.month, instance.start.day, instance.start.hour,
        instance.id, filename
    )


def _name_observation_demoddata(instance, filename):
    """Return a filepath for DemodData formatted by Observation ID"""
    # On change of the string bellow, change it also at api/views.py
    return 'data_obs/{0}/{1}/{2}/{3}/{4}/{5}'.format(
        instance.observation.start.year, instance.observation.start.month,
        instance.observation.start.day, instance.observation.start.hour, instance.observation.id,
        filename
    )


def _select_audio_storage():
    return S3Boto3Storage() if settings.USE_S3_STORAGE_FOR_AUDIO else DefaultStorage()


def _select_waterfall_storage():
    return S3Boto3Storage() if settings.USE_S3_STORAGE_FOR_WATERFALL else DefaultStorage()


def _select_data_storage():
    return S3Boto3Storage() if settings.USE_S3_STORAGE_FOR_DATA else DefaultStorage()


def validate_image(fieldfile_obj):
    """Validates image size"""
    filesize = fieldfile_obj.file.size
    megabyte_limit = 2.0
    if filesize > megabyte_limit * 1024 * 1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))


class Station(models.Model):
    """Model for SatNOGS ground stations."""
    owner = models.ForeignKey(
        User, related_name="ground_stations", on_delete=models.SET_NULL, null=True, blank=True
    )
    name = models.CharField(max_length=45)
    image = models.ImageField(upload_to='ground_stations', blank=True, validators=[validate_image])
    alt = models.PositiveIntegerField(null=True, blank=True, help_text='In meters above sea level')
    lat = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(90), MinValueValidator(-90)],
        help_text='eg. 38.01697'
    )
    lng = models.FloatField(
        null=True,
        blank=True,
        validators=[MaxValueValidator(180), MinValueValidator(-180)],
        help_text='eg. 23.7314'
    )
    # https://en.wikipedia.org/wiki/Maidenhead_Locator_System
    qthlocator = models.CharField(max_length=8, blank=True)
    featured_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    testing = models.BooleanField(default=True)
    last_seen = models.DateTimeField(null=True, blank=True)
    status = models.IntegerField(choices=STATION_STATUSES, default=0)
    violator_scheduling = models.IntegerField(
        choices=STATION_VIOLATOR_SCHEDULING_CHOICES, default=0
    )
    horizon = models.PositiveIntegerField(help_text='In degrees above 0', default=10)
    description = models.TextField(max_length=500, blank=True, help_text='Max 500 characters')
    client_version = models.CharField(max_length=45, blank=True)
    target_utilization = models.IntegerField(
        validators=[MaxValueValidator(100), MinValueValidator(0)],
        help_text='Target utilization factor for '
        'your station',
        null=True,
        blank=True
    )
    client_id = models.CharField(max_length=128, blank=True)
    # Basic client configuration
    satnogs_soapy_rx_device = models.CharField(max_length=40, blank=True)
    satnogs_antenna = models.CharField(max_length=40, blank=True)
    satnogs_rx_samp_rate = models.PositiveIntegerField(null=True, blank=True)
    satnogs_rf_gain = models.FloatField(null=True, blank=True)

    class Meta:
        ordering = ['-status']
        indexes = [models.Index(fields=['-status', 'id'])]

    def get_image(self):
        """Return the image of the station or the default image if there is a defined one"""
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        return settings.STATION_DEFAULT_IMAGE

    @property
    def is_online(self):
        """Return true if station is online"""
        try:
            heartbeat = self.last_seen + timedelta(minutes=int(settings.STATION_HEARTBEAT_TIME))
            return heartbeat > now()
        except TypeError:
            return False

    @property
    def is_offline(self):
        """Return true if station is offline"""
        return not self.is_online

    @property
    def has_location(self):
        """Return true if station location is defined"""
        if self.alt is None or self.lat is None or self.lng is None:
            return False
        return True

    @property
    def is_testing(self):
        """Return true if station is online and in testing mode"""
        if self.is_online:
            if self.status == 1:
                return True
        return False

    def state(self):
        """Return the station status in html format"""
        if not self.status:
            return format_html('<span style="color:red;">Offline</span>')
        if self.status == 1:
            return format_html('<span style="color:orange;">Testing</span>')
        return format_html('<span style="color:green">Online</span>')

    @property
    def success_rate(self):
        """Return the success rate of the station - successful observation over failed ones"""
        rate = cache.get('station-{0}-rate'.format(self.id))
        if not rate:
            observations = self.observations.exclude(testing=True).exclude(status__range=(0, 99))
            stats = observations.aggregate(
                bad=Count('pk', filter=Q(status__range=(-100, -1))),
                good=Count('pk', filter=Q(status__gte=100)),
                failed=Count('pk', filter=Q(status__lt=100))
            )
            good_count = 0 if stats['good'] is None else stats['good']
            bad_count = 0 if stats['bad'] is None else stats['bad']
            failed_count = 0 if stats['failed'] is None else stats['failed']
            total = good_count + bad_count + failed_count
            if total:
                rate = int(100 * ((bad_count + good_count) / total))
                cache.set('station-{0}-rate'.format(self.id), rate, 60 * 60 * 6)
            else:
                rate = False
        return rate

    def __str__(self):
        if self.pk:
            return "%d - %s" % (self.pk, self.name)
        return "%s" % (self.name)

    def clean(self):
        if re.search('[^\x20-\x7E\xA0-\xFF]', self.name, re.IGNORECASE):
            raise ValidationError(
                {
                    'name': (
                        'Please use characters that belong to ISO-8859-1'
                        ' (https://en.wikipedia.org/wiki/ISO/IEC_8859-1).'
                    )
                }
            )
        if re.search('[^\n\r\t\x20-\x7E\xA0-\xFF]', self.description, re.IGNORECASE):
            raise ValidationError(
                {
                    'description': (
                        'Please use characters that belong to ISO-8859-1'
                        ' (https://en.wikipedia.org/wiki/ISO/IEC_8859-1).'
                    )
                }
            )

    def update_status(self, created: bool = False):
        """
        Update the status of the station

        :param created: Whether the model is being created
        """
        if not created:
            current_status = self.status
            if self.is_offline:
                self.status = 0
            elif self.testing:
                self.status = 1
            else:
                self.status = 2
            self.save()
            if self.status != current_status:
                StationStatusLog.objects.create(station=self, status=self.status)
        else:
            StationStatusLog.objects.create(station=self, status=self.status)


class AntennaType(models.Model):
    """Model for antenna types."""
    name = models.CharField(max_length=25, unique=True)

network/users/forms.py
"""Django users forms for SatNOGS Network"""
from django import forms

from network.users.models import User


class UserForm(forms.ModelForm):
    """Model Form class for User objects"""
    class Meta:
        model = User
        fields = ("first_name", "last_name")

network/base/views/generic.py
"""Django base views for SatNOGS Network"""
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from network.base.decorators import staff_required
from network.base.tasks import fetch_data, update_future_observations_with_new_tle_sets, \
    update_future_observations_with_new_transmitter_details


def index(request):
    """View to render index page."""
    return render(
        request, 'base/home.html', {
            'mapbox_id': settings.MAPBOX_MAP_ID,
            'mapbox_token': settings.MAPBOX_TOKEN
        }
    )


def robots(request):
    """Returns response for robots.txt requests"""
    data = render(request, 'robots.txt', {'environment': settings.ENVIRONMENT})
    response = HttpResponse(data, content_type='text/plain; charset=utf-8')
    return response


@staff_required
def settings_site(request):
    """View to render settings page."""
    if request.method == 'POST':
        fetch_data.delay()
        update_future_observations_with_new_tle_sets.delay()
        update_future_observations_with_new_transmitter_details.delay()
        messages.success(request, 'Data fetching task was triggered successfully!')
        return redirect(reverse('users:view_user', kwargs={"username": request.user.username}))
    return render(request, 'base/settings_site.html')

network/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load tags %}
{% load cache %}
{% load humanize %}

{% block title %}
  {% if user == request.user %} - Dashboard{% else %} - User: {{ user.username }}{% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col col-md-12">
      <h2>
        {% cache 3600 observations-avatar user.email %}
          <img src="{{ user.email|gravatar_url:50 }}" class="img-avatar"/>
        {% endcache %}
        {{ user.displayname }}
      <h2>
    </div>

    <div class="col d-none d-lg-flex justify-content-end align-items-center">
      <span class="user-actions">
        {% if user == request.user %}
            <a class="btn btn-primary" role=button" href="{% url 'users:update_user' %}">
              <span class="bi bi-gear" aria-hidden="true"></span> Settings
           </a>
           <a class="btn btn-primary"  role=button" href="{% url 'account_email' %}">
              <span class="bi bi-envelope-at" aria-hidden="true"></span> Email
           </a>
           <a class="btn btn-info"  role=button" data-toggle="modal" data-target="#APIModal" href="#">
              <span class="bi bi-Key" aria-hidden="true"></span> API Key
           </a>
        {% endif %}
      </span>
    </div>

    <div class="col d-flex d-lg-none justify-content-end align-items-center">
      <span class="user-actions">
        {% if user == request.user %}
            <a class="btn btn-primary" role=button" href="{% url 'users:update_user' %}">
              <span class="bi bi-gear" aria-hidden="true"></span>
           </a>
           <a class="btn btn-primary"  role=button" href="{% url 'account_email' %}">
              <span class="bi bi-envelope-at" aria-hidden="true"></span>
           </a>
           <a class="btn btn-info"  role=button" data-toggle="modal" data-target="#APIModal" href="#">
              <span class="bi bi-Key" aria-hidden="true"></span>
           </a>
        {% endif %}
      </span">
    </div>
  </div>


  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="stations-tab" data-toggle="tab" data-target="#stations" type="button" role="tab" aria-controls="stations" aria-selected="true">Ground Stations</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="observations-tab" data-toggle="tab" data-target="#observations" type="button" role="tab" aria-controls="observations" aria-selected="false">Recent Observations</button>
    </li>
  </ul>

  <div class="tab-content" id="user-tab-content">
    <div class="tab-pane fade show active" id="stations" role="tabpanel" aria-labelledby="stations-tab">
      {% if stations %}
        <div class="row">
          <div class="col-md-12">
            <table class="table table-sm table-hover my-2">
              <thead class="bg-light">
                <th>ID</th>
                <th>Name</th>
                <th>Location</th>
                <th>Total</th>
                <th>Future</th>
                <th>Antennas</th>
              </thead>
              <tbody>
                {% for station in stations %}
                  <tr class="station-row clickable-row" data-href="{% url 'base:station_view' station_id=station.id %}">
                    <td>
                      <a href="{% url 'base:station_view' station_id=station.id %}">
                        <span class="station
                                     {% if station.last_seen %}
                                       badge badge-{{ station.get_status_display|lower }}
                                     {% else %}
                                       badge badge-future
                                     {% endif %}"
                              data-toggle="tooltip"
                              data-placement="bottom"
                              title="{% if station.last_seen %}
                                       Seen {{ station.last_seen|timesince }} ago
                                     {% else %}
                                       Never seen online
                                     {% endif %}">
                          {{ station.id }}
                        </span>
                      </a>
                    </td>
                    <td>
                      {{ station.name }}
                    </td>
                      <td>
                        {% if station.has_location %}
                          {% if station.qthlocator %}
                            <span data-toggle="tooltip" data-placement="bottom"
                                  title="{{ station.lat|floatformat:-3 }}°, {{ station.lng|floatformat:-3 }}°">
                            {{ station.qthlocator }}
                          {% else %}
                            {{ station.lat|floatformat:-1 }}°, {{ station.lng|floatformat:-1 }}°
                          {% endif %}
                          @{{ station.alt}}m
                        {% else %}
                          Location not defined
                        {% endif %}
                      </td>
                    <td>
                      <a href="{% url 'base:observations_list' %}?station={{ station.id }}" class="badge badge-success badge-pill" data-toggle="tooltip" data-placement="bottom" title={% if not station.success_rate %}"No data" {% else %}"{{ station.success_rate }}% Success" {% endif %}>
                        {{ station.total_obs }}
                      </a>
                    </td>
                    <td>
                      <a href="{% url 'base:observations_list' %}?future=1&good=0&bad=0&unknown=0&failed=0&station={{ station.id }}" class="badge badge-info badge-pill">
                        {{ station.future_obs }}
                      </a>
                    </td>
                    <td class="antennas">
                      {% for antenna in station.antennas.all %}
                        <span class="antenna-pill" data-toggle="tooltip" data-placement="bottom"
                              title="{% for range in antenna.frequency_ranges.all %} {{ range.min_frequency|frq }} - {{ range.max_frequency|frq }}&#xA{% endfor %}">
                          {{ antenna.antenna_type }} ({{ antenna.bands}})
                        </span>
                      {% endfor %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      {% else %}
        <div class="row">
          <div class="col-md-12 notice">
            <p>{{ user.displayname }} is not an owner of any ground stations.</p>
          </div>
        </div>
      {% endif %}

      {% if user == request.user %}
        <div class="row">
          <div class="col-md-12">
            <a class="btn btn-outline-dark" href="{% url 'base:station_edit' %}">
              <span class="bi bi-plus" aria-hidden="true"></span> Add Ground Station
            </a>
          </div>
        </div>
      {% endif %}
    </div>

    <div class="tab-pane fade" id="observations" role="tabpanel" aria-labelledby="observations-tab">
      {% if observations %}
        <div class="row">
          <div class="col-md-12">
            <table class="table table-sm table-hover my-2">
              <thead class="bg-light">
                <th>ID</th>
                <th>Satellite</th>
                <th>Frequency</th>
                <th>Mode</th>
                <th>Timeframe</th>
                <th>Station</th>
              </thead>
              <tbody>
                {% for observation in observations %}
                  <tr class="clickable-row" data-href="{% url 'base:observation_view' observation_id=observation.id %}">
                    <td class="text-nowrap">
                      <a href="{% url 'base:observation_view' observation_id=observation.id %}">
                        {% if observation.is_future %}
                          <span class="badge badge-future">{{ observation.id }}</span>
                        {% elif observation.status < -100 %}
                          <span class="badge badge-failed">{{ observation.id }}</span>
                        {% elif observation.status >= -100  and observation.status < 0 %}
                          <span class="badge badge-bad">{{ observation.id }}</span>
                        {% elif observation.status >= 0  and observation.status < 100 %}
                          <span class="badge badge-unknown">{{ observation.id }}</span>
                        {% elif observation.status >= 100 %}
                          <span class="badge badge-good">{{ observation.id }}</span>
                        {% endif %}
                      </a>
                    </td>
                    <td class="text-nowrap">
                      <a href="#" data-toggle="modal" data-target="#SatelliteModal" data-id="{{ observation.satellite.norad_cat_id }}">
                        {{ observation.satellite.name }}
                      </a>
                    </td>
                    <td class="text-nowrap">
                      {% if observation.center_frequency %}
                        {{ observation.center_frequency|frq }}
                      {% else %}
                        {{ observation.transmitter_downlink_low|frq }}
                      {% endif %}
                    </td>
                    <td class="text-nowrap">
                      <span data-toggle="tooltip" data-placement="bottom" title="{{ observation.transmitter_description }}">
                        {{ observation.transmitter_mode|default:"-" }}
                      </span>
                      <span>
                        {{ observation.transmitter_baud|floatformat|default:"" }}
                      </span>
                    </td>
                    <td class="text-nowrap">
                      <span data-toggle="tooltip" data-placement="bottom" title="{{ observation.start|naturaltime }}">
                        <span class="datetime-date">{{ observation.start|date:"Y-m-d" }}</span>
                        <span class="datetime-time">{{ observation.start|date:"H:i:s" }}</span><br>
                      </span>
                      <span data-toggle="tooltip" data-placement="bottom" title="{{ observation.end|naturaltime }}">
                        <span class="datetime-date">{{ observation.end|date:"Y-m-d" }}</span>
                        <span class="datetime-time">{{ observation.end|date:"H:i:s" }}</span>
                      </span>
                    </td>
                    <td>
                      {% if observation.ground_station %}
                        <a href="{% url 'base:station_view' station_id=observation.ground_station.id %}">
                          {{ observation.ground_station }}
                        </a>
                      {% endif %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      {% else %}
        <div class="row">
          <div class="col-md-12 notice">
            <p>{{ user.displayname }} is not an author of any observation.</p>
          </div>
        </div>
      {% endif %}

      {% if can_schedule and user == request.user %}
        <div class="row">
          <div class="col-md-12">
            <a class="btn btn-outline-dark" href="{% url 'base:observation_new' %}">
              <span class="bi bi-plus" aria-hidden="true"></span>
              New Observation
            </a>
          </div>
        </div>
      {% endif %}
    </div>
  </div>

  {% if user == request.user %}
    <!-- API Modal -->
    <div class="modal fade" id="APIModal" tabindex="-1" role="dialog" aria-labelledby="APIModalTitle" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title" id="APIModalTitle">API Key</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id="api-key">
              <div>You can use this token to interact with the API.</div>
              <div>
                <code>{{ token }}</code>
              </div>
            </div>
            <div id="renew-api-message" hidden>
              <p>Do you really want to renew your API Key?</p>
              <p>If you change it, your station(s) will need a configuration update in order to use the new API Key.</p>
              <p>Until this update is done, your station(s) will not be able to get jobs or upload any artifacts for the completed ones.</p>
            </div>
          </div>
          <div class="modal-footer justify-content-between">
            <form id="renew-api-form" method="post" action="{% url 'users:update_user_token' %}" hidden>
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Yes, renew the API Key</button>
            </form>
            <button class="btn btn-danger" id="api-modal-button">Renew API Key</button>
            <button type="button" class="btn btn-outline-dark" id="api-modal-close-button" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  {% endif %}

  {% include 'includes/satellite.html' %}
{% endblock content %}

{% block javascript %}
  <script src="{% static 'js/satellite.js' %}"></script>
  <script src="{% static 'js/api-renew.js' %}"></script>
{% endblock javascript %}